name: Deploy website to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
